apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-claim-serve
  labels:
    app: health-claim
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-claim
  template:
    metadata:
      labels:
        app: health-claim
    spec:
      containers:
      - name: health-claim-serve
        image: health-claim-serve:v1
        ports:
        - containerPort: 80
        env:
        - name: MODEL_PATH
          value: "/models"
---
apiVersion: v1
kind: Service
metadata:
  name: health-claim-service
spec:
  selector:
    app: health-claim
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
